apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    name: kafka
  name: kafka-service
spec:
  clusterIP: None
  ports:
  - name: kafka-port
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
    id: "0"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
